version: '3.4'
networks:
   wavesenterprise-network:
     driver: bridge
services:
  oracle-1:
    image: akafakir/easyoracle-webapp-app:1.0.0-SNAPSHOT-20201212232431-eed109a.dirty
    restart: always
    container_name: oracle-1
    hostname: oracle-1
    environment:
      - SPRING_PROFILES_ACTIVE=oracle1
      - SPRING_DATASOURCE_URL=jdbc:postgresql://178.154.233.23:5432/db_oracle_remote
    expose:
      - 8081
    ports:
      - 8081:8081
    networks:
      - wavesenterprise-network
  oracle-2:
    image: akafakir/easyoracle-webapp-app:1.0.0-SNAPSHOT-20201212232431-eed109a.dirty
    restart: always
    container_name: oracle-2
    hostname: oracle-2
    environment:
      - SPRING_PROFILES_ACTIVE=oracle2
      - SPRING_DATASOURCE_URL=jdbc:postgresql://178.154.233.23:5432/db_oracle_remote
    expose:
      - 8082
    ports:
      - 8082:8082
    networks:
      - wavesenterprise-network
  oracle-3:
    image: akafakir/easyoracle-webapp-app:1.0.0-SNAPSHOT-20201212232431-eed109a.dirty
    restart: always
    container_name: oracle-3
    hostname: oracle-3
    environment:
      - SPRING_PROFILES_ACTIVE=oracle3
      - SPRING_DATASOURCE_URL=jdbc:postgresql://178.154.233.23:5432/db_oracle_remote
    expose:
      - 8083
    ports:
      - 8083:8083
    networks:
      - wavesenterprise-network