we-oauth2:
  additional:
    clientsDetails:
      - clientId: api-easyoracle-app
        clientSecret: $2a$10$aUmlg4BxumTHis05iMhpf.j4wgrAOKtnCrMUiFnaZzYmA27HY3Zry # easyoracle-app-secret
        resourceIds:
          - vst-oauth2
          - vst-identity
          - vst-files
          - easyoracle-app
        scope:
          - read
          - vst-client
        authorizedGrantTypes:
          - password
          - refresh_token
        registeredRedirectUri:
          - http://localhost/test
        authorities:
          - ROLE_TRUSTED_CLIENT
          - WE_IDENTITY_READ

      - clientId: easyoracle-app
        clientSecret: $2a$10$3iiULmtayf6Xttykse1DpOi/Skp7B4PgqKsksz6THRLam0.peVXwi # easyoracle-app-secret
        resourceIds:
          - vst-identity
          - vst-files
          - vst-oauth2
        scope:
          - read
        authorizedGrantTypes:
          - client_credentials
        authorities:
          - ROLE_TRUSTED_CLIENT
          - WE_IDENTITY_READ
          - WE_IDENTITY_WRITE
          - WE_PRIVACY_READ
          - WE_PRIVACY_WRITE
          - WE_OAUTH2_WRITE
          - WE_OAUTH2_READ
